server:
  port: 9090
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: el-aparato
          uri: http://localhost:8082
          predicates:
            - Path=/productos/**
            - Path=/ventas/**
  security:
    oauth2:
      client:
        provider:
          keycloak-test:
            issuer-uri: http://localhost:8080/realms/elAparatoGalvis
        registration:
          keycloak-test:
            authorization-grant-type: authorization_code
            client-id: api-gateway-client
            client-secret: CmWjvITAtqIlQObvF0pq6lTRrQtF2JUX
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
            scope:
              - openid
logging:
  level:
    org:
      springframework:
        security: DEBUG

